service: sls-py-webmonitor

custom:
  stage: ${opt:stage, self:provider.stage}
  func_prefix: ${self:service}-${self:custom.stage}
  private: false # Change to 'true' if you don't want to 


provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-1
  memorySize: 128
  cfLogs: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SITE_TABLE_NAME}"
  environment:
    SERVERLESS_PROJECT: ${self:service}
    SERVERLESS_STAGE: ${self:custom.stage}
    SITE_TABLE_NAME: ${self:service}-sites-${self:custom.stage}

functions:
  dashboard:
    handler: handler.dashboard
    name: ${self:custom.func_prefix}-dashboard
    description: "${self:service}: Show dashboard page as a static html"
    events:
      - http:
          path: sites
          method: get
          cors: true
          private: ${self:custom.private}
  register:
    handler: handler.register
    name: ${self:custom.func_prefix}-register
    description: "${self:service}: Register target website to DynamoDB"
    events:
      - http:
          path: sites/register
          method: post
          cors: true
          private: ${self:custom.private}
  remove:
    handler: handler.remove
    name: ${self:custom.func_prefix}-remove
    description: "${self:service}: Remove target website from DynamoDB"
    events:
      - http:
          path: sites/remove
          method: post
          cors: true
          private: ${self:custom.private}


resources:
  Resources:
    SitesDynamo:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.SITE_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
